steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/django_on_cloudrun:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/django_on_cloudrun:$SHORT_SHA', 'gcr.io/$PROJECT_ID/django_on_cloudrun:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/django_on_cloudrun:$SHORT_SHA', 'gcr.io/$PROJECT_ID/django_on_cloudrun:$BRANCH_NAME']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/django_on_cloudrun:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/django_on_cloudrun:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/django_on_cloudrun:$BRANCH_NAME']
- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'beta', 'run', 'deploy', '--region', 'europe-west1', '--image', 'gcr.io/$PROJECT_ID/django_on_cloudrun', '--platform', 'managed']
images:
- 'gcr.io/$PROJECT_ID/django_on_cloudrun'